Improvement/element details layout
netuitive-community-packages/netuitive-packages-aws-elasticache pull request #15
Opened 2017-09-26 21:24 UTC by Createor

Fixing #13.

2017-09-27 12:05 UTC, TheConnMan approved these changes

2017-09-29 20:23 UTC, rclagett requested changes
build failed?

2017-09-29 20:29 UTC, Createor commented
Builds are failing because the package validator doesn't like the number format used here: https://github.com/netuitive-community-packages/netuitive-packages-aws-elasticache/blob/dev/policies/aws.elasticache.memcached.-.elevated.swap.usage.json#L21
I have reported that bug here: https://github.com/Netuitive/netuitive-package-validator/issues/8

2017-09-29 20:37 UTC, rclagett approved these changes

2017-10-03 20:46 UTC, merged